name = "alexle135-homepage"
main = "worker.js"
compatibility_date = "2024-01-01"

# Astro Static Site mit API-Endpoints
[build]
command = "pnpm build"

# Routes für die Domain
routes = [
  { pattern = "alexle135.de/*", zone_name = "alexle135.de" },
  { pattern = "www.alexle135.de/*", zone_name = "alexle135.de" }
]

# Environment Variables (werden über Cloudflare Dashboard gesetzt)
[vars]
# RSS_FEED_CACHE_TTL = "300"  # 5 Minuten Cache für RSS-Feeds
