backend:
  name: github
  repo: alexle/alexle-vsco
  branch: main
  commit_messages:
    create: 'feat(cms): create {{collection}} “{{slug}}”'
    update: 'chore(cms): update {{collection}} “{{slug}}”'
    delete: 'chore(cms): delete {{collection}} “{{slug}}”'
    uploadMedia: 'chore(media): upload “{{path}}”'
    deleteMedia: 'chore(media): delete “{{path}}”'
local_backend: true
publish_mode: editorial_workflow
media_folder: public/media/uploads
public_folder: /media/uploads
site_url: https://alexle135.de
logo_url: /media/alex-gemini.webp
slug:
  encoding: ascii
  clean_accents: true
  sanitize_replacement: '-'
collections:
  - name: hero
    label: Hero Bereich
    format: json
    delete: false
    files:
      - file: src/content/hero/hero.json
        label: Hero Inhalt
        name: hero
        fields:
          - { name: title, label: Titel, widget: string }
          - { name: subtitle, label: Untertitel, widget: text, required: false }
          - { name: cta, label: CTA-Text, widget: string, required: false }
          - { name: ctaHref, label: CTA-Link (optional), widget: string, required: false }
          - { name: media, label: Medien (Bild/Video), widget: file, allow_multiple: false, required: false }

  - name: about
    label: Über mich Seite
    delete: false
    files:
      - file: src/content/about/about.md
        label: Über mich
        name: about
        fields:
          - { name: title, label: Titel, widget: string }
          - { name: profileImage, label: Profilbild, widget: image, required: false }
          - { name: profileImageAlt, label: Alternativtext, widget: string, required: false }
          - { name: body, label: Inhalt, widget: markdown }

  - name: services
    label: Leistungen
    format: json
    delete: false
    files:
      - file: src/content/services/services.json
        label: Leistungsübersicht
        name: services
        fields:
          - label: Services
            name: items
            widget: list
            summary: '{{fields.title}}'
            fields:
              - { name: title, label: Titel, widget: string }
              - { name: description, label: Beschreibung, widget: text }
              - { name: icon, label: Icon, widget: string, required: false }
              - { name: color, label: Farbe (intern), widget: string, required: false }
              - { name: tags, label: Tags, widget: list, required: false }

  - name: skills
    label: Skills & Expertise
    format: json
    delete: false
    files:
      - file: src/content/skills/skills.json
        label: Skillliste
        name: skills
        fields:
          - label: Skills
            name: items
            widget: list
            summary: '{{fields.name}} – {{fields.percentage}}%'
            fields:
              - { name: name, label: Name, widget: string }
              - { name: percentage, label: Prozent, widget: number, value_type: int, min: 0, max: 100 }
              - { name: category, label: Kategorie, widget: string, required: false }

  - name: projects
    label: Projekte
    folder: src/content/projects
    create: true
    slug: '{{slug}}'
    extension: md
    format: frontmatter
    sortable_fields: ['title', 'date']
    fields:
      - { name: title, label: Titel, widget: string }
      - { name: summary, label: Kurzbeschreibung, widget: text }
      - { name: date, label: Datum, widget: datetime, required: false }
      - { name: tags, label: Tags, widget: list, required: false }
      - { name: heroImage, label: Hero-Bild, widget: image, required: false }
      - { name: repo, label: Repository-URL, widget: string, required: false }
      - { name: demo, label: Demo-URL, widget: string, required: false }
      - { name: body, label: Inhalt, widget: markdown }

  - name: legal
    label: Rechtliches
    delete: false
    files:
      - file: src/content/legal/impressum.md
        label: Impressum
        name: impressum
        fields:
          - { name: title, label: Titel, widget: string, default: Impressum }
          - { name: description, label: Beschreibung, widget: string, required: false }
          - { name: body, label: Inhalt, widget: markdown }
      - file: src/content/legal/datenschutz.md
        label: Datenschutzerklärung
        name: datenschutz
        fields:
          - { name: title, label: Titel, widget: string, default: Datenschutzerklärung }
          - { name: description, label: Beschreibung, widget: string, required: false }
          - { name: body, label: Inhalt, widget: markdown }

  - name: ki-news
    label: KI-News Feed
    format: json
    delete: false
    files:
      - file: src/content/ki-news/index.json
        label: Feed-Daten
        name: feed
        fields:
          - { name: lastUpdate, label: Letzte Aktualisierung, widget: datetime }
          - label: Artikel
            name: articles
            widget: list
            summary: '{{fields.title}} – {{fields.source}}'
            fields:
              - { name: title, label: Titel, widget: string }
              - { name: summary, label: Zusammenfassung, widget: text }
              - { name: url, label: Quelle URL, widget: string }
              - { name: source, label: Quelle, widget: string }
              - { name: publishedAt, label: Veröffentlicht am, widget: datetime }
              - { name: tags, label: Tags, widget: list, required: false }
              - { name: relevanceScore, label: Relevanz (0-100), widget: number, min: 0, max: 100 }
              - { name: language, label: Sprache, widget: string, required: false }
              - { name: priority, label: Priorität, widget: number, required: false }
          - label: Statistiken
            name: stats
            widget: object
            fields:
              - { name: totalFeeds, label: Feeds gesamt, widget: number }
              - { name: totalArticles, label: Artikel gesamt, widget: number }
              - { name: uniqueArticles, label: Einzigartige Artikel, widget: number }
              - { name: finalArticles, label: Finale Artikel, widget: number }
