backend:
  name: github
  repo: arn0ld87/alexle-vsco
  branch: main
  base_url: https://cms-auth.YOUR-WORKER-SUBDOMAIN.workers.dev
  auth_endpoint: /auth
  commit_messages:
    create: 'feat(cms): create {{collection}} "{{slug}}"'
    update: 'chore(cms): update {{collection}} "{{slug}}"'
    delete: 'chore(cms): delete {{collection}} "{{slug}}"'
    uploadMedia: 'chore(media): upload "{{path}}"'
    deleteMedia: 'chore(media): delete "{{path}}"'

local_backend: true
publish_mode: editorial_workflow
media_folder: public/media/uploads
public_folder: /media/uploads

collections:
  # Hero Section
  - name: hero
    label: "🎯 Hero Section"
    format: json
    delete: false
    editor:
      preview: true
    files:
      - file: src/content/hero/hero.json
        label: Hero Content
        name: hero
        fields:
          - { name: title, label: Titel, widget: string, required: true }
          - { name: subtitle, label: Untertitel, widget: text, required: true }
          - { name: cta, label: CTA-Button Text, widget: string, required: true }
          - { name: media, label: 'Medien (Video/Bild URL)', widget: string, required: true, hint: 'Pfad zur Video oder Bild Datei, z.B. media/logoneu.mp4' }

  # About Section
  - name: about
    label: "👤 Über mich"
    delete: false
    files:
      - file: src/content/about/about.md
        label: Über mich
        name: about
        fields:
          - { name: title, label: Titel, widget: string, required: true }
          - { name: profileImage, label: Profilbild, widget: image, required: true }
          - { name: profileImageAlt, label: Profilbild Alt-Text, widget: string, required: true }
          - { name: body, label: Inhalt (Markdown), widget: markdown, required: true }

  # Services
  - name: services
    label: "🛠️ Leistungen"
    format: json
    delete: false
    files:
      - file: src/content/services/services.json
        label: Services Liste
        name: services
        fields:
          - label: Services
            name: items
            widget: list
            fields:
              - { name: title, label: Titel, widget: string, required: true }
              - { name: description, label: Beschreibung, widget: text, required: true }
              - { name: icon, label: 'Icon CSS Klasse', widget: string, required: false, hint: 'z.B. fas fa-network-wired' }
              - { name: color, label: Farbe, widget: select, options: ['blue', 'purple', 'green', 'orange', 'red', 'yellow'], required: false }

  # Skills
  - name: skills
    label: "💡 Kompetenzen"
    format: json
    delete: false
    files:
      - file: src/content/skills/skills.json
        label: Skills Liste
        name: skills
        fields:
          - label: Skills
            name: items
            widget: list
            fields:
              - { name: name, label: Skill Name, widget: string, required: true }
              - { name: percentage, label: 'Erfahrung %', widget: number, value_type: int, min: 0, max: 100, required: true }
              - { name: category, label: Kategorie/Beschreibung, widget: string, required: true }

  # Projects
  - name: projects
    label: "🚀 Projekte"
    folder: src/content/projects
    create: true
    slug: "{{slug}}"
    extension: md
    format: frontmatter
    editor:
      preview: true
    fields:
      - { name: title, label: Projekt Titel, widget: string, required: true }
      - { name: summary, label: Kurzbeschreibung, widget: text, required: true }
      - { name: tags, label: Tags, widget: list, required: false, hint: 'z.B. KI, DevOps, Netzwerk' }
      - { name: heroImage, label: Hero-Bild, widget: image, required: false, hint: 'Header-Bild für Projekt' }
      - { name: body, label: 'Projekt-Details (Markdown)', widget: markdown, required: true }

  # Legal Pages
  - name: legal
    label: "⚖️ Rechtliches"
    delete: false
    files:
      - file: src/content/legal/impressum.md
        label: Impressum
        name: impressum
        fields:
          - { name: title, label: Titel, widget: string, default: Impressum }
          - { name: body, label: Inhalt, widget: markdown, required: true }
      - file: src/content/legal/datenschutz.md
        label: Datenschutzerklärung
        name: datenschutz
        fields:
          - { name: title, label: Titel, widget: string, default: Datenschutzerklärung }
          - { name: body, label: Inhalt, widget: markdown, required: true }

  # KI News (Read-Only for manual edits, auto-updated via GitHub Action)
  - name: ki-news
    label: "🤖 KI-News (Auto-Update)"
    format: json
    delete: false
    editor:
      preview: false
    files:
      - file: src/content/ki-news/index.json
        label: KI-Nachrichten Feed
        name: ki-news
        fields:
          - { name: lastUpdate, label: Letztes Update, widget: datetime, required: true }
          - label: Artikel
            name: articles
            widget: list
            fields:
              - { name: title, label: Titel, widget: string }
              - { name: summary, label: Zusammenfassung, widget: text }
              - { name: url, label: URL, widget: string }
              - { name: source, label: Quelle, widget: string }
              - { name: publishedAt, label: Veröffentlicht am, widget: datetime }
              - { name: tags, label: Tags, widget: list }
              - { name: relevanceScore, label: Relevanz-Score, widget: number, value_type: int, min: 0, max: 100 }
          - label: Statistiken
            name: stats
            widget: object
            fields:
              - { name: totalFeeds, label: Gesamt Feeds, widget: number, value_type: int }
              - { name: totalArticles, label: Gesamt Artikel, widget: number, value_type: int }
              - { name: uniqueArticles, label: Einzigartige Artikel, widget: number, value_type: int }
              - { name: finalArticles, label: Finale Artikel, widget: number, value_type: int }
